const types = {
  LOADING: 'LOADING',
  LOADING_DONE: 'LOADING_DONE',
  ERROR: 'ERROR',

  // set params
  SET_PARAMS_MOVIES_DETAIL: 'SET_PARAMS_MOVIES_DETAIL',

  // get All Movies
  GET_ALL_MOVIES: 'GET_ALL_MOVIES',
  GET_ALL_MOVIES_SUCCESS: 'GET_ALL_MOVIES_SUCCESS',
  GET_ALL_MOVIES_FAILURE: 'GET_ALL_MOVIES_FAILURE',

  //get Movies Popular
  GET_MOVIES_POPULAR: 'GET_MOVIES_POPULAR',
  GET_MOVIES_POPULAR_SUCCESS: 'GET_MOVIES_POPULAR_SUCCESS',
  GET_MOVIES_POPULAR_FAILURE: 'GET_MOVIES_POPULAR_FAILURE',

  //get Movies Top Rated
  GET_MOVIES_TOP: 'GET_MOVIES_TOP',
  GET_MOVIES_TOP_SUCCESS: 'GET_MOVIES_TOP_SUCCESS',
  GET_MOVIES_TOP_FAILURE: 'GET_MOVIES_TOP_FAILURE',

  //get Movies Trending
  GET_MOVIES_TRENDING: 'GET_MOVIES_TRENDING',
  GET_MOVIES_TRENDING_SUCCESS: 'GET_MOVIES_TRENDING_SUCCESS',
  GET_MOVIES_TRENDING_FAILURE: 'GET_MOVIES_TRENDING_FAILURE',

  //get Movies Now Playing
  GET_MOVIES_PLAY: 'GET_MOVIES_PLAY',
  GET_MOVIES_PLAY_SUCCESS: 'GET_MOVIES_PLAY_SUCCESS',
  GET_MOVIES_PLAY_FAILURE: 'GET_MOVIES_PLAY_FAILURE',

  //get Movies Now Airing
  GET_MOVIES_AIRING: 'GET_MOVIES_AIRING',
  GET_MOVIES_AIRING_SUCCESS: 'GET_MOVIES_AIRING_SUCCESS',
  GET_MOVIES_AIRING_FAILURE: 'GET_MOVIES_AIRING_FAILURE',

  //get Movies Upcoming
  GET_MOVIES_UPCOMING: 'GET_MOVIES_UPCOMING',
  GET_MOVIES_UPCOMING_SUCCESS: 'GET_MOVIES_UPCOMING_SUCCESS',
  GET_MOVIES_UPCOMING_FAILURE: 'GET_MOVIES_UPCOMING_FAILURE',

  //get Movies On TV
  GET_MOVIES_ON: 'GET_MOVIES_ON',
  GET_MOVIES_ON_SUCCESS: 'GET_MOVIES_ON_SUCCESS',
  GET_MOVIES_ON_FAILURE: 'GET_MOVIES_ON_FAILURE',

  //get Movies Videos
  GET_MOVIES_VIDEOS: 'GET_MOVIES_VIDEOS',
  GET_MOVIES_VIDEOS_SUCCESS: 'GET_MOVIES_VIDEOS_SUCCESS',
  GET_MOVIES_VIDEOS_FAILURE: 'GET_MOVIES_VIDEOS_FAILURE',

  //get Movies Reviews
  GET_MOVIES_REVIEWS: 'GET_MOVIES_REVIEWS',
  GET_MOVIES_REVIEWS_SUCCESS: 'GET_MOVIES_REVIEWS_SUCCESS',
  GET_MOVIES_REVIEWS_FAILURE: 'GET_MOVIES_REVIEWS_FAILURE',

  //get Movies Recommendations
  GET_MOVIES_RECOMMENDED: 'GET_MOVIES_RECOMMENDED',
  GET_MOVIES_RECOMMENDED_SUCCESS: 'GET_MOVIES_RECOMMENDED_SUCCESS',
  GET_MOVIES_RECOMMENDED_FAILURE: 'GET_MOVIES_RECOMMENDED_FAILURE',

  //get Movies Similar
  GET_MOVIES_SIMILAR: 'GET_MOVIES_SIMILAR',
  GET_MOVIES_SIMILAR_SUCCESS: 'GET_MOVIES_SIMILAR_SUCCESS',
  GET_MOVIES_SIMILAR_FAILURE: 'GET_MOVIES_SIMILAR_FAILURE',

  // get Movie by id
  GET_MOVIES_BY_ID: 'GET_MOVIES_BY_ID',
  GET_MOVIES_BY_ID_SUCCESS: 'GET_MOVIES_BY_ID_SUCCESS',
  GET_MOVIES_BY_ID_FAILURE: 'GET_MOVIES_BY_ID_FAILURE',
};

export default types;
